version: '3'

services:
  zookeeper:
    container_name: ex-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "22181:2181"

  kafka:
    container_name: ex-kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPIC: "my_topic:1:3"
    depends_on:
      - zookeeper